#!/usr/bin/env python3
"""Build data/names_tr.json: the Turkish common name of each species.json taxon.

Sources & Methodology:

  1. TÜBİVES (Türkiye Bitkileri Veri Servisi / TÜBİTAK)
     Flora of Turkey and the East Aegean Islands (P.H. Davis, Vols 1-11).
     Standard national herbarium and vernacular name archive for the Turkish flora.

  2. Türkiye Bitkileri Listesi (Damarlı Bitkiler) / BizimBitkiler
     Güner, A., Aslan, S., Ekim, T., Vural, M., Babaç, M.T. (edlr.).
     Nezahat Gökyiğit Botanik Bahçesi ve Flora Araştırmaları Derneği Yayını,
     İstanbul, 2012. ISBN: 978-605-60425-7-7.
     The definitive national checklist establishing standardized Turkish plant names.

  3. Orman Genel Müdürlüğü (OGM) & Tarım ve Orman Bakanlığı
     Orman Ağaç ve Çalıları Taksonomisi ve Türkiye Kültür Bitkileri Envanteri.

Architecture (3-tier resolution matching build_names_pt.py):
  1. CURATED_TR: Hand-verified species and infraspecific variety names keyed by exact `sci`
     matching species.json. Prevents variety flattening collisions (e.g. broccoli vs cauliflower vs kale).
  2. GENUS_NAME: Authoritative Turkish genus vernacular name fallback for forestry and
     agricultural genera documented in BizimBitkiler / OGM.
  3. Taxa with no verified Turkish name are left out entirely, cleanly falling back
     to the Latin binomial (`<i>Pinus brutia</i>`), matching the honest-data design principle.

Run:
  python3 scripts/build_names_tr.py
"""
import collections
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPECIES = ROOT / "data" / "species.json"
OUT = ROOT / "data" / "names_tr.json"

# Curated, authoritative Turkish vernacular names from TÜBİVES, BizimBitkiler (Güner et al. 2012),
# and OGM forestry/agricultural records.
# Key: exact scientific binomial or infraspecific name as spelled in species.json.
# Value: "primary_name|synonym1|synonym2"
CURATED_TR = {
    # --- İğne Yapraklılar / Conifers (Pinaceae, Cupressaceae, Taxaceae) ---
    "Abies amabilis": "pasifik göknarı|güzel göknar",
    "Abies balsamea": "balsam göknarı|balsam",
    "Abies concolor": "gümüşi göknar|kolorado göknarı",
    "Abies pindrow": "pindrov göknarı|himalaya göknarı",
    "Cedrus deodara": "himalaya sediri",
    "Cupressus arizonica": "arizona servisi|mavi servi",
    "Larix decidua": "avrupa melezi|melez",
    "Picea abies": "avrupa ladini|adi ladin",
    "Pinus brutia": "kızılçam|çam",
    "Pinus canariensis": "kanarya çamı",
    "Pinus halepensis": "halep çamı",
    "Pinus mugo": "dağ çamı|bodur çam",
    "Pinus pinaster": "sahil çamı",
    "Pinus pinea": "fıstık çamı",
    "Pinus ponderosa": "sarıçam (amerikan)|ağır çam",
    "Pinus radiata": "monterey çamı",
    "Pinus roxburghii": "himalaya çamı|chir çamı",
    "Pinus sylvestris": "sarıçam",
    "Pinus sylvestris var. mongolica": "moğol sarıçamı",
    "Pinus taeda": "loblolly çamı",
    "Pinus elliottii ssp. elliottii": "elliott çamı",
    "Taxodium distichum": "bataklık servisi",

    # --- Geniş Yapraklı Orman Ağaçları ve Çalılar ---
    "Acer caesium": "himalaya akçaağacı",
    "Acer saccharum": "şeker akçaağacı",
    "Ailanthus altissima": "kokarağaç|cennet ağacı",
    "Betula pubescens": "tüylü huş",
    "Carpinus betulus": "adi gürgen|gürgen",
    "Castanea dentata": "amerikan kestanesi",
    "Castanea mollissima": "çin kestanesi",
    "Castanea sativa": "anadolu kestanesi|tatlı kestane|kestane",
    "Ceratonia siliqua": "keçiboynuzu|harnup",
    "Fagus grandifolia": "amerikan kayını",
    "Fagus sylvatica": "avrupa kayını|adi kayın",
    "Fagus sylvatica ssp. sylvatica": "avrupa kayını|adi kayın",
    "Fraxinus excelsior": "adi dişbudak|dişbudak",
    "Gleditsia triacanthos": "üç dikenli gladiçya|gladiçya|yabani keçiboynuzu",
    "Liquidambar styraciflua": "amerikan sığla ağacı",
    "Populus deltoides": "kara kavak (kanada)|kanada kavağı",
    "Populus euphratica": "fırat kavağı",
    "Quercus agrifolia": "kaliforniya meşesi",
    "Quercus alba": "ak meşe",
    "Quercus ilex": "pırnal meşesi",
    "Quercus robur": "saplı meşe|adi meşe|meşe",
    "Quercus suber": "mantar meşesi",
    "Robinia pseudoacacia": "yalancı akasya|beyaz salkım|akasya",

    # --- Meyve, Yemiş ve Bahçe Ağaçları / Çalıları ---
    "Anacardium occidentale": "kaju|kaju cevizi",
    "Annona atemoya": "atemoya",
    "Annona cherimola": "çerimoya",
    "Annona cherimola x Annona squamosa": "atemoya",
    "Annona muricata": "graviola|dikenli anona",
    "Annona squamosa": "anona|şeker elması",
    "Araucaria angustifolia": "parana çamı|brezilya arokaryası",
    "Artocarpus altilis": "ekmek ağacı",
    "Artocarpus heterophyllus": "jak meyvesi|jak",
    "Bertholletia excelsa": "brezilya cevizi|brezilya kestanesi",
    "Carya illinoinensis": "pekan cevizi|pekan",
    "Carica papaya": "papaya",
    "Citrofortunella x microcarpa": "kalamondin|misket portakalı",
    "Citrus aurantiifolia": "misket limonu|laym",
    "Citrus aurantium": "turunç",
    "Citrus aurantium ssp. bergamia": "bergamot",
    "Citrus deliciosa": "akdeniz mandalinası|mandalina",
    "Citrus grandis": "ağaç kavunu|şadok|pomelo",
    "Citrus japonica": "kamkat|kumkuat",
    "Citrus latifolia": "tahiti limonu|fars misket limonu",
    "Citrus limon": "limon",
    "Citrus medica": "ağaç kavunu|sedir elması",
    "Citrus × microcarpa": "kalamondin|kamkat",
    "Citrus paradisi": "greyfurt",
    "Citrus reticulata": "mandalina",
    "Citrus sinensis": "portakal",
    "Citrus unshiu": "satsuma mandalinası|rize mandalinası",
    "Corylus avellana": "fındık|adi fındık",
    "Corylus colurna var. colurna": "türk fındığı|ağaç fındığı",
    "Corylus maxima": "tombul fındık|lambert fındığı",
    "Cydonia oblonga": "ayva",
    "Diospyros kaki": "trabzon hurması|cennet elması",
    "Diospyros nigra": "kara sapot|çikolata meyvesi",
    "Elaeagnus angustifolia": "kuş iğdesi|iğde",
    "Eriobotrya japonica": "malta eriği|yeni dünya",
    "Eugenia uniflora": "pitanga|surinam kirazı",
    "Ficus carica": "incir|adi incir",
    "Ficus elastica": "kauçuk ağacı|kauçuk",
    "Ficus benghalensis": "banyan ağacı|bengal inciri",
    "Ficus sycomorus": "firavun inciri|mısır inciri",
    "Fragaria x ananassa": "çilek|bahçe çileği",
    "Fragaria vesca": "yaban çileği",
    "Garcinia mangostana": "mangostan|mangostin",
    "Juglans nigra": "kara ceviz",
    "Juglans regia": "ceviz|adi ceviz",
    "Laurus nobilis": "akdeniz defnesi|defne",
    "Litchi chinensis": "liçi|kral meyvesi",
    "Macadamia integrifolia": "makademya fındığı|makademya",
    "Malus domestica": "elma|kültür elması",
    "Malus sylvestris": "yabani elma",
    "Mangifera indica": "mango",
    "Manilkara zapota": "sapodilla|çiko meyvesi",
    "Morus alba": "ak dut|beyaz dut|dut",
    "Morus nigra": "kara dut",
    "Morus rubra": "kırmızı dut",
    "Musa acuminata": "muz|anamur muzu",
    "Musa acuminata x balbisiana": "muz",
    "Musa balbisiana": "yabani muz",
    "Musa textilis": "abaka|manila keneviri",
    "Myrtus communis": "mersin|hambeles",
    "Olea europaea": "zeytin|delice",
    "Opuntia ficus-indica": "frenk inciri|dikenli incir|hint inciri",
    "Passiflora edulis": "çarkıfelek|marakuya",
    "Passiflora edulis var. edulis": "mor çarkıfelek|marakuya",
    "Passiflora edulis var. flavicarpa": "sarı çarkıfelek|marakuya",
    "Passiflora laurifolia": "portakal çarkıfeleği",
    "Passiflora mollissima": "muz çarkıfeleği|kuruba",
    "Persea americana": "avokado",
    "Persea americana ssp. guatemalan": "guatemala avokadosu|avokado",
    "Persea americana ssp. mexican": "meksika avokadosu|avokado",
    "Persea americana ssp. west indian": "batı hint avokadosu|avokado",
    "Phoenix dactylifera": "hurma|hurma ağacı",
    "Physalis peruviana": "altın çilek|güveyfeneri",
    "Pistacia vera": "antep fıstığı|fıstık",
    "Pouteria sapota": "mamey sapote",
    "Prunus amygdalus": "badem",
    "Prunus armeniaca": "kayısı",
    "Prunus avium": "kiraz|tatlı kiraz",
    "Prunus cerasus": "vişne",
    "Prunus domestica": "erik|adi erik",
    "Prunus persica": "şeftali",
    "Prunus salicina": "japon eriği",
    "Psidium cattleyanum": "çilek guavası",
    "Psidium guajava": "guava",
    "Punica granatum": "nar",
    "Pyrus communis": "armut|kültür armudu",
    "Pyrus pyrifolia": "asya armudu|nashi",
    "Ribes nigrum": "siyah frenküzümü",
    "Ribes rubrum": "kırmızı frenküzümü|frenküzümü",
    "Ribes uva-crispa": "bektaşi üzümü",
    "Rubus idaeus ssp. idaeus": "ahududu|ağaççileği",
    "Rubus occidentalis": "siyah ahududu",
    "Spondias mombin": "sarı mombin|cajá",
    "Spondias purpurea": "kırmızı mombin",
    "Tamarindus indica": "demirhindi",
    "Theobroma cacao": "kakao ağacı|kakao",
    "Vaccinium angustifolium": "yaban mersini (dar yapraklı)",
    "Vaccinium corymbosum": "yüksek boylu yaban mersini|mavi yemiş",
    "Vaccinium macrocarpon": "turnayemişi|büyük meyveli kızılcık",
    "Vaccinium myrtillus": "yaban mersini|çobanüzümü",
    "Vitis labrusca": "isabella üzümü|kokulu üzüm",
    "Vitis vinifera": "asma|üzüm",
    "Ziziphus mauritiana": "hint hünnabı",

    # --- Tarım Bitkileri, Tahıllar, Baklagiller ve Sebzeler ---
    "Abelmoschus esculentus": "bamya",
    "Abelmoschus manihot": "aibou|manihot bamyası",
    "Allium ampeloprasum": "pırasa|yabani pırasa",
    "Allium cepa": "soğan|kuru soğan",
    "Allium cepa var. aggregatum": "arpacık soğanı|şalot soğanı",
    "Allium cepa var. cepa": "baş soğan|kuru soğan",
    "Allium chinense": "çin soğanı",
    "Allium fistulosum": "yeşil soğan|gal soğanı",
    "Allium sativum": "sarımsak",
    "Allium schoenoprasum": "frenk soğanı|yaprak soğanı",
    "Allium tuberosum": "çin sarımsağı|yaprak sarımsağı",
    "Amaranthus caudatus": "horozibiği|kuyruklu amarant",
    "Amaranthus cruentus": "kırmızı amarant",
    "Amaranthus hypochondriacus": "amarant",
    "Anethum graveolens": "dereotu",
    "Apium graveolens": "kereviz",
    "Apium graveolens var. dulce": "sap kerevizi",
    "Apium graveolens var. rapaceum": "kök kerevizi",
    "Arachis hypogaea": "yer fıstığı",
    "Asparagus officinalis": "kuşkonmaz",
    "Avena sativa": "yulaf",
    "Beta vulgaris": "pancar",
    "Beta vulgaris var. cicla": "pazı|yaprak pancarı",
    "Beta vulgaris var. crassa": "yem pancarı",
    "Beta vulgaris var. flavescens": "pazı",
    "Beta vulgaris var. saccharifera": "şeker pancarı",
    "Brassica carinata": "etiyopya hardalı",
    "Brassica chinensis": "çin lahanası|pakçoy",
    "Brassica juncea": "kahverengi hardal|hint hardalı",
    "Brassica napus": "kanola|kolza",
    "Brassica napus var. napobrassica": "şalgam lahanası|rutabaga",
    "Brassica nigra": "kara hardal",
    "Brassica oleracea var. acephala": "karalahana|yaprak lahana",
    "Brassica oleracea var. botrytis": "karnabahar",
    "Brassica oleracea var. capitata": "baş lahana|beyaz lahana|lahana",
    "Brassica oleracea var. gemmifera": "brüksel lahanası",
    "Brassica oleracea var. gongyloides": "alabaş|kolrabi",
    "Brassica oleracea var. italica": "brokoli",
    "Brassica rapa": "şalgam|şalgam turbu",
    "Brassica rapa Gaisin gr.": "çin lahanası",
    "Brassica rapa Pak Choi": "pakçoy|çin lahanası",
    "Brassica rapa var. rapifera": "şalgam turbu|şalgam",
    "Cajanus cajan": "güvercin bezelyesi",
    "Cannabis sativa ssp. indica": "hint keneviri|kenevir",
    "Capsicum annuum": "biber|sivri biber|kapya",
    "Capsicum baccatum var. pendulum": "çile biberi",
    "Capsicum frutescens": "çin biberi|tabasko biberi|acı süs biberi",
    "Carthamus tinctorius": "aspir",
    "Chenopodium quinoa": "kinoa",
    "Cicer arietinum": "nohut",
    "Citrullus lanatus": "karpuz",
    "Colocasia esculenta": "gölevez|kolokas|taro",
    "Colocasia esculenta var. antiquorum": "gölevez|kolokas",
    "Coriandrum sativum": "kişniş",
    "Crocus sativus": "safran",
    "Cucumis melo": "kavun",
    "Cucumis sativus": "salatalık|hıyar",
    "Cucurbita moschata": "bal kabağı|helvacı kabağı",
    "Cucurbita pepo": "sakız kabağı|kabak",
    "Cuminum cyminum": "kimyon",
    "Cynara cardunculus": "enginar|yabani enginar",
    "Cynodon dactylon": "ayrık otu|köpekdişi ayrığı",
    "Cyperus rotundus": "topalak",
    "Daucus carota": "havuç",
    "Eruca sativa": "roka",
    "Fagopyrum esculentum": "karabuğday|greçka",
    "Foeniculum vulgare": "rezene",
    "Glycine max": "soya fasulyesi|soya",
    "Gossypium barbadense": "pima pamuğu|ada pamuğu",
    "Gossypium herbaceum": "yerli pamuk|levant pamuğu",
    "Gossypium hirsutum": "pamuk|uplant pamuğu",
    "Helianthus annuus": "ayçiçeği",
    "Helianthus tuberosus": "yer elması",
    "Hordeum vulgare": "arpa",
    "Humulus lupulus": "şerbetçiotu",
    "Ipomoea aquatica": "su ıspanağı|su gündüzsefası",
    "Ipomoea aquatica var. reptans": "su ıspanağı",
    "Ipomoea batatas": "tatlı patates",
    "Lactuca sativa var. capitata": "baş marul|göbekli marul",
    "Lathyrus cicera": "cılban|yabani mürdümük",
    "Lathyrus hirsutus": "tüylü mürdümük",
    "Lathyrus ochrus": "sarı mürdümük",
    "Lathyrus sativus": "mürdümük",
    "Lens culinaris": "mercimek",
    "Linum usitatissimum": "keten",
    "Lupinus albus": "termiye|acı bakla|ak acıbakla",
    "Lupinus angustifolius": "mavi acıbakla",
    "Lupinus luteus": "sarı acıbakla",
    "Manihot esculenta": "manyak|kassava",
    "Marrubium vulgare": "bozotu|it sineği otu",
    "Medicago arabica": "arap yoncası",
    "Medicago falcata": "sarı çiçekli yonca",
    "Medicago lupulina": "şerbetçiotu yoncası|kara yonca",
    "Medicago minima": "küçük yonca",
    "Medicago orbicularis": "düğmeli yonca",
    "Medicago polymorpha": "pıtrak yoncası",
    "Medicago rigidula": "sert yonca",
    "Medicago sativa": "yonca|kaba yonca",
    "Medicago scutellata": "salyangoz yoncası",
    "Medicago truncatula": "fıçı yoncası",
    "Mentha piperita": "tıbbi nane|nane",
    "Mentha pulegium": "yarpuz|filiskin",
    "Mentha spicata var. crispa": "kıvırcık nane",
    "Momordica charantia": "kudret narı",
    "Moringa oleifera": "moringa|baget ağacı",
    "Nicotiana rustica": "maraş tütünü|hasankeyf tütünü",
    "Nicotiana tabacum": "tütün",
    "Ocimum basilicum": "fesleğen|reyhan",
    "Origanum majorana": "mercanköşk",
    "Origanum onites": "izmir kekiği|bilyalı kekik",
    "Origanum vulgare": "istanbul kekiği|yabani kekik",
    "Oryza glaberrima": "afrika pirinci",
    "Oryza sativa": "çeltik|pirinç",
    "Oryza sativa ssp. indica": "indika pirinci",
    "Oryza sativa ssp. javanica": "cava pirinci",
    "Panicum miliaceum": "darı|ak darı",
    "Papaver somniferum": "haşhaş",
    "Pastinaca sativa": "yabani havuç|pastinaka",
    "Pennisetum glaucum": "inci darısı",
    "Petroselinum crispum": "maydanoz",
    "Phaseolus coccineus": "bombom fasulye|ateş fasulyesi",
    "Phaseolus lunatus": "lima fasulyesi",
    "Phaseolus vulgaris": "fasulye|kuru fasulye",
    "Pimpinella anisum": "anason",
    "Pisum sativum": "bezelye",
    "Portulaca oleracea": "semizotu",
    "Raphanus sativus": "turp|fındık turpu",
    "Raphanus sativus var. oleiferus": "yağlık turp|yemlik turp",
    "Ricinus communis": "hint yağı bitkisi|keneotu",
    "Rosmarinus officinalis": "biberiye",
    "Saccharum officinarum": "şeker kamışı",
    "Salvia officinalis": "tıbbi adaçayı|adaçayı",
    "Secale cereale": "çavdar",
    "Sesamum indicum": "susam",
    "Setaria italica": "cin darısı|kuş yemi",
    "Sinapis alba": "beyaz hardal",
    "Solanum aethiopicum": "etiyopya patlıcanı",
    "Solanum lycopersicum": "domates",
    "Solanum melongena": "patlıcan",
    "Solanum muricatum": "pepino",
    "Solanum nigrum": "itüzümü|köpeküzümü",
    "Solanum tuberosum": "patates",
    "Sorghum bicolor": "süpürge darısı|sorgum",
    "Sorghum bicolor var. sweet": "tatlı sorgum|şeker darısı",
    "Sorghum x drummondii": "sudan otu",
    "Spinacia oleracea": "ıspanak",
    "Stevia rebaudiana": "şekerotu|stevya",
    "Thymus serpyllum": "yabani kekik|kır kekiği",
    "Thymus vulgaris": "bahçe kekiği|kekik",
    "Trifolium alexandrinum": "iskenderiye üçgülü|berseem",
    "Trifolium arvense": "tavşantopu|tarla üçgülü",
    "Trifolium campestre": "kır üçgülü",
    "Trifolium dubium": "küçük sarı üçgül",
    "Trifolium fragiferum": "çilek üçgülü",
    "Trifolium hybridum": "melez üçgül",
    "Trifolium incarnatum": "kırmızı üçgül|kan üçgülü",
    "Trifolium pratense": "çayır üçgülü",
    "Trifolium repens": "ak üçgül|beyaz üçgül",
    "Trifolium resupinatum": "fars üçgülü|ters üçgül",
    "Trifolium subterraneum": "yeraltı üçgülü",
    "Trifolium tomentosum": "yünlü üçgül",
    "Triticum aestivum": "ekmeklik buğday|buğday",
    "Triticum durum": "makarnalık buğday",
    "Triticum spelta": "spelta|kızıl buğday|dinkel",
    "Vicia benghalensis": "mor fiğ",
    "Vicia ervilia": "burçak",
    "Vicia faba": "bakla",
    "Vicia narbonensis": "koca fiğ",
    "Vicia pannonica": "macar fiği",
    "Vicia sativa ssp. nigra": "kara fiğ|yabani fiğ",
    "Vicia sativa ssp. sativa": "adi fiğ|fiğ",
    "Vicia villosa ssp. villosa": "tüylü fiğ",
    "Vigna aconitifolia": "güve fasulyesi|mat fasulyesi",
    "Vigna angularis": "adzuki fasulyesi",
    "Vigna mungo": "urad fasulyesi|kara maş",
    "Vigna radiata": "maş fasulyesi",
    "Vigna subterranea": "bambara yer fıstığı",
    "Vigna unguiculata": "börülce|karnıkara",
    "Vigna unguiculata ssp. sesquipedalis": "metrelik börülce|uzun börülce",
    "Vigna unguiculata ssp. unguiculata": "börülce|karnıkara",
    "Zea mays": "mısır",
    "Zea mays ssp. mays": "mısır",
    "Zea mays ssp. saccharata": "tatlı mısır|şeker mısırı",

    # --- Tropikal / Egzotik / Endüstriyel Türler ---
    "Acacia auriculiformis": "papua akasyası",
    "Acacia catechu": "kateşu akasyası",
    "Acacia dealbata": "gümüşi akasya|mimoza",
    "Acacia farnesiana": "amber akasyası",
    "Acacia nilotica": "arap zamkı ağacı|zamk akasyası",
    "Acacia saligna": "mavi yapraklı akasya",
    "Acacia senegal": "senegal akasyası",
    "Adansonia digitata": "baobab",
    "Ananas comosus": "ananas",
    "Azadirachta indica": "nim ağacı|neem",
    "Bambusa vulgaris": "bambu|adi bambu",
    "Bixa orellana": "anatto|ruku ağacı",
    "Boehmeria nivea": "rami|ramie",
    "Calotropis procera": "sodom elması|ipek ağacı",
    "Camellia sinensis": "çay|çay bitkisi",
    "Camellia sinensis var. assamica": "assam çayı|çay",
    "Camellia sinensis var. sinensis": "çin çayı|çay",
    "Casuarina equisetifolia": "demir ağacı|avustralya çamı",
    "Ceiba pentandra": "kapok ağacı|ipek pamuğu",
    "Cinnamomum camphora": "kafur ağacı",
    "Cinnamomum verum": "seylan tarçını|tarçın",
    "Cocos nucifera": "hindistan cevizi",
    "Coffea arabica": "arap kahvesi|kahve",
    "Coffea canephora": "robusta kahve",
    "Curcuma longa": "zerdeçal",
    "Curcuma zedoaria": "cedvar",
    "Cymbopogon citratus": "limon otu",
    "Cymbopogon nardus var. lenabatu": "sitronella otu",
    "Cymbopogon nardus var. mahapengiri": "sitronella otu",
    "Dendrocalamus asper": "dev bambu",
    "Dendrocalamus strictus": "katı bambu|kalküta bambusu",
    "Eichhornia crassipes": "su sümbülü",
    "Elaeis guineensis": "yağ palmiyesi",
    "Elettaria cardamomum": "kakule",
    "Eucalyptus camaldulensis": "okaliptüs|sıtma ağacı",
    "Eucalyptus globulus": "mavi okaliptüs",
    "Eucalyptus globulus ssp. maidenii": "maiden okaliptüsü",
    "Eucalyptus globulus var. bicostata": "güney mavi okaliptüsü",
    "Eucalyptus globulus var. pseudoglobulus": "victoria mavi okaliptüsü",
    "Eucalyptus grandis": "gül okaliptüs",
    "Eucalyptus robusta": "bataklık okaliptüsü",
    "Eugenia aromatica": "karanfil|karanfil ağacı",
    "Grevillea robusta": "ipek meşesi|avustralya gümüş meşesi",
    "Hevea brasiliensis": "kauçuk ağacı",
    "Ilex paraguariensis": "mate çayı|yerba mate",
    "Indigofera tinctoria": "çivitotu",
    "Jacaranda mimosifolia": "mavi jakaranda|jakaranda",
    "Jatropha curcas": "jatrofa|frenk inciri ağacı",
    "Melaleuca leucadendra": "çay ağacı|melalöka",
    "Melia azedarach": "tespih ağacı|hindistan leylağı",
    "Myroxylon balsamum": "peru pelesengi|balsam ağacı",
    "Myroxylon balsamum var. perei.": "peru pelesengi",
    "Paulownia tomentosa": "kiri ağacı|imparator ağacı",
    "Piper betle": "betel yaprağı",
    "Piper nigrum": "karabiber",
    "Pogostemon cablin": "paçuli",
    "Pueraria lobata": "kudzu",
    "Pueraria phaseoloides": "tropikal kudzu",
    "Samanea saman": "yağmur ağacı",
    "Schinus molle": "yalancı karabiber|pembe biber",
    "Schizolobium parahybum": "guapuruvu ağacı",
    "Senna spectabilis": "kassod|göz alıcı sena",
    "Sesbania grandiflora": "tori ağacı|bataklık sesbanyası",
    "Spartium junceum": "katırtırnağı",
    "Swietenia macrophylla": "büyük yapraklı maun|honduras maunu",
    "Swietenia mahogani": "küba maunu|maun",
    "Syzygium cumini": "camun meyvesi|cava eriği",
    "Tectona grandis": "tik ağacı|teak",
    "Terminalia catappa": "hint bademi|kızıl badem",
    "Vanilla planifolia": "vanilya",
    "Vetiveria zizanioides": "vetiver",
    "Vitex agnus-castus": "hayıt|iffet ağacı",
    "Zingiber officinale": "zencefil",
}

# Standard Turkish genus vernacular names from BizimBitkiler (Güner et al. 2012) and OGM forestry records.
# Used as tier-2 fallback only when CURATED_TR has no species-level record.
GENUS_NAME = {
    "Abies": "göknar",
    "Acacia": "akasya",
    "Acer": "akçaağaç",
    "Agave": "sabırlık",
    "Agropyron": "ayrık",
    "Ailanthus": "kokarağaç",
    "Albizia": "gülibrişim",
    "Allium": "soğan",
    "Alnus": "kızılağaç",
    "Aloe": "sarısabır",
    "Amaranthus": "horozibiği",
    "Anacardium": "kaju",
    "Ananas": "ananas",
    "Andropogon": "sakalsızot",
    "Annona": "anona",
    "Apium": "kereviz",
    "Arachis": "yer fıstığı",
    "Araucaria": "arokarya",
    "Aristida": "üçkılçık",
    "Arrhenatherum": "yulafotu",
    "Artocarpus": "ekmek ağacı",
    "Asparagus": "kuşkonmaz",
    "Astragalus": "geven",
    "Atriplex": "unluca",
    "Avena": "yulaf",
    "Bambusa": "bambu",
    "Beta": "pancar",
    "Betula": "huş",
    "Brachiaria": "çim darısı",
    "Brassica": "lahana",
    "Bromus": "brom",
    "Cajanus": "güvercin bezelyesi",
    "Callitris": "servi çamı",
    "Calopogonium": "kalopogonyum",
    "Camellia": "çay",
    "Cannabis": "kenevir",
    "Capsicum": "biber",
    "Carica": "papaya",
    "Carpinus": "gürgen",
    "Carthamus": "aspir",
    "Carya": "pekan",
    "Cassia": "sinameki",
    "Castanea": "kestane",
    "Casuarina": "demir ağacı",
    "Cedrus": "sedir",
    "Celtis": "çitlembik",
    "Cenchrus": "pıtraklı darı",
    "Centrosema": "kelebek fasulyesi",
    "Ceratonia": "keçiboynuzu",
    "Cercis": "erguvan",
    "Chenopodium": "kazayağı",
    "Chrysanthemum": "kasımpatı",
    "Cicer": "nohut",
    "Cinnamomum": "tarçın",
    "Citrullus": "karpuz",
    "Citrus": "narenciye",
    "Cocos": "hindistan cevizi",
    "Coffea": "kahve",
    "Colocasia": "gölevez",
    "Coriandrum": "kişniş",
    "Cornus": "kızılcık",
    "Corylus": "fındık",
    "Crataegus": "alıç",
    "Crocus": "safran",
    "Crotalaria": "çıngırakotu",
    "Cucumis": "hıyar",
    "Cucurbita": "kabak",
    "Cuminum": "kimyon",
    "Cupressus": "servi",
    "Curcuma": "zerdeçal",
    "Cymbopogon": "limon otu",
    "Cynara": "enginar",
    "Cynodon": "ayrık otu",
    "Cyperus": "topalak",
    "Dactylis": "domuz ayrığı",
    "Dalbergia": "gül ağacı",
    "Daucus": "havuç",
    "Dendrocalamus": "dev bambu",
    "Desmodium": "yapışkanotu",
    "Digitaria": "çim darısı",
    "Dioscorea": "yams",
    "Diospyros": "hurma",
    "Echinochloa": "darıcan",
    "Elaeagnus": "iğde",
    "Elaeis": "yağ palmiyesi",
    "Eleusine": "korakan",
    "Eragrostis": "aşk otu",
    "Eriobotrya": "malta eriği",
    "Eruca": "roka",
    "Erythrina": "mercan ağacı",
    "Eucalyptus": "okaliptüs",
    "Eugenia": "surinam kirazı",
    "Fagopyrum": "karabuğday",
    "Fagus": "kayın",
    "Festuca": "yumak",
    "Ficus": "incir",
    "Foeniculum": "rezene",
    "Fragaria": "çilek",
    "Fraxinus": "dişbudak",
    "Garcinia": "mangostan",
    "Ginkgo": "mabet ağacı",
    "Gleditsia": "gladiçya",
    "Glycine": "soya",
    "Gossypium": "pamuk",
    "Grevillea": "grevilya",
    "Helianthus": "ayçiçeği",
    "Hevea": "kauçuk ağacı",
    "Hibiscus": "ebegümeci",
    "Hordeum": "arpa",
    "Humulus": "şerbetçiotu",
    "Ilex": "çobanpüskülü",
    "Indigofera": "çivitotu",
    "Inga": "inga",
    "Ipomoea": "tatlı patates",
    "Jacaranda": "jakaranda",
    "Jatropha": "jatrofa",
    "Juglans": "ceviz",
    "Juniperus": "ardıç",
    "Lactuca": "marul",
    "Larix": "melez",
    "Lathyrus": "mürdümük",
    "Laurus": "defne",
    "Lavandula": "lavanta",
    "Leucaena": "kurşun ağacı",
    "Linum": "keten",
    "Liquidambar": "sığla",
    "Litchi": "liçi",
    "Lolium": "çim",
    "Lotus": "gazalboynuzu",
    "Luffa": "lif kabağı",
    "Lupinus": "acıbakla",
    "Macadamia": "makademya",
    "Macroptilium": "siratro",
    "Malus": "elma",
    "Mangifera": "mango",
    "Manihot": "manyak",
    "Manilkara": "sapodilla",
    "Medicago": "yonca",
    "Melaleuca": "çay ağacı",
    "Melia": "tespih ağacı",
    "Melilotus": "kokulu yonca",
    "Mentha": "nane",
    "Moringa": "moringa",
    "Morus": "dut",
    "Mucuna": "kadife fasulyesi",
    "Musa": "muz",
    "Myrtus": "mersin",
    "Nicotiana": "tütün",
    "Ocimum": "fesleğen",
    "Olea": "zeytin",
    "Opuntia": "frenk inciri",
    "Origanum": "kekik",
    "Oryza": "pirinç",
    "Panicum": "darı",
    "Papaver": "haşhaş",
    "Paspalum": "su darısı",
    "Passiflora": "çarkıfelek",
    "Pastinaca": "pastinaka",
    "Paulownia": "pavlonya",
    "Pennisetum": "kofa darısı",
    "Persea": "avokado",
    "Petroselinum": "maydanoz",
    "Phalaris": "kuşyemi",
    "Phaseolus": "fasulye",
    "Phoenix": "hurma",
    "Phleum": "kedi kuyruğu",
    "Phyllostachys": "bambu",
    "Physalis": "güveyfeneri",
    "Picea": "ladin",
    "Pinus": "çam",
    "Piper": "biber",
    "Pistacia": "fıstık",
    "Pisum": "bezelye",
    "Plantago": "karnıyarık otu",
    "Platanus": "çınar",
    "Poa": "salkımotu",
    "Populus": "kavak",
    "Portulaca": "semizotu",
    "Prosopis": "meskit",
    "Prunus": "erik",
    "Pseudotsuga": "duglas",
    "Psidium": "guava",
    "Pueraria": "kudzu",
    "Punica": "nar",
    "Pyrus": "armut",
    "Quercus": "meşe",
    "Raphanus": "turp",
    "Rhus": "sumak",
    "Ribes": "frenküzümü",
    "Ricinus": "hint yağı",
    "Robinia": "yalancı akasya",
    "Rosa": "gül",
    "Rosmarinus": "biberiye",
    "Rubus": "böğürtlen",
    "Saccharum": "şeker kamışı",
    "Salix": "söğüt",
    "Salvia": "adaçayı",
    "Sambucus": "mürver",
    "Secale": "çavdar",
    "Senna": "sinameki",
    "Sesamum": "susam",
    "Sesbania": "sesbanya",
    "Setaria": "cin darısı",
    "Sinapis": "hardal",
    "Solanum": "itüzümü",
    "Sorghum": "sorgum",
    "Spartium": "katırtırnağı",
    "Spinacia": "ıspanak",
    "Stipa": "kavotu",
    "Stylosanthes": "kalemotu",
    "Swietenia": "maun",
    "Syzygium": "karanfil",
    "Tamarindus": "demirhindi",
    "Tamarix": "ılgın",
    "Taxodium": "bataklık servisi",
    "Taxus": "porsuk",
    "Tectona": "tik",
    "Terminalia": "badem ağacı",
    "Theobroma": "kakao",
    "Thuja": "mazı",
    "Thymus": "kekik",
    "Tilia": "ıhlamur",
    "Trifolium": "üçgül",
    "Triticum": "buğday",
    "Ulmus": "karaağaç",
    "Urena": "malva",
    "Urochloa": "çim darısı",
    "Vaccinium": "yaban mersini",
    "Vanilla": "vanilya",
    "Viburnum": "kartopu",
    "Vicia": "fiğ",
    "Vigna": "börülce",
    "Vitex": "hayıt",
    "Vitis": "asma",
    "Zea": "mısır",
    "Zingiber": "zencefil",
    "Ziziphus": "hünnap",
}


def clean_name(s):
    if not s:
        return ""
    s = s.strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s


def build():
    species_list = json.load(open(SPECIES, encoding="utf-8"))
    species_sci_set = {s["sci"].strip() for s in species_list}

    # Data integrity assertion: prevent dead keys in CURATED_TR
    unknown = sorted(set(CURATED_TR) - species_sci_set)
    if unknown:
        sys.exit(f"CURATED_TR keys absent from species.json: {', '.join(unknown)}")

    out = {}
    counts = collections.Counter()

    for sp in species_list:
        sid = str(sp["id"])
        sci = sp["sci"].strip()
        genus = sci.split()[0]

        # Tier 1: Exact species / variety curated match
        if sci in CURATED_TR:
            parts = [clean_name(p) for p in CURATED_TR[sci].split("|") if p.strip()]
            if parts:
                entry = {"nome": parts[0]}
                if len(parts) > 1:
                    entry["aka"] = parts[1:]
                out[sid] = entry
                counts["curated"] += 1
                continue

        # Tier 2: Genus fallback
        if genus in GENUS_NAME:
            out[sid] = {"nome": GENUS_NAME[genus]}
            counts["genus"] += 1
            continue

        # Tier 3: Deliberately omitted -> app cleanly falls back to Latin binomial

    # Write formatted json
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=None, separators=(",", ":"))
        f.write("\n")

    total_named = len(out)
    pct = total_named / len(species_list) * 100
    print(f"Generated {OUT.name}: {total_named} / {len(species_list)} taxa covered ({pct:.1f}%).")
    print(f"  - Curated species/varieties: {counts['curated']}")
    print(f"  - Genus fallback names:      {counts['genus']}")
    print(f"  - Omitted (Latin fallback):  {len(species_list) - total_named}")


if __name__ == "__main__":
    build()
